[package]
name = "smiles_with_selectors"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1.4.0"
petgraph = "0.6.2"
regex = "1.6.0"
strum = "0.24.1"
strum_macros = "0.24.3"
